import React from 'react';
import {
    AlertCircle,
    ArrowRight,
    Award,
    Bookmark,
    Book,
    BookOpen,
    Box,
    Briefcase,
    Brain,
    Calendar,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronUp,
    Clipboard,
    ClipboardCheck,
    ClipboardList,
    Clock,
    Copy,
    CreditCard,
    Download,
    Edit,
    ExternalLink,
    Eye,
    File,
    FileText,
    Filter,
    Flag,
    FolderOpen,
    GraduationCap,
    Gift,
    Globe,
    HelpCircle,
    Heart,
    Headphones,
    Home,
    Image,
    Info,
    Laptop,
    LampDesk,
    Lightbulb,
    Link,
    List,
    Lock,
    Mail,
    MapPin,
    Medal,
    Menu,
    MessageSquare,
    Mic,
    Monitor,
    Moon,
    MoreHorizontal,
    Music,
    Package,
    Paperclip,
    Phone,
    Play,
    Plus,
    PlusCircle,
    Presentation,
    School,
    Search,
    Send,
    Settings,
    Share,
    ShieldCheck,
    ShoppingBag,
    ShoppingCart,
    Smile,
    Star,
    Sun,
    Tag,
    ThumbsUp,
    Timer,
    Trash,
    Trophy,
    Upload,
    User,
    Users,
    UserCheck,
    Video,
    VideoOff,
    Zap,
} from 'lucide-react';

// Create a typed mapping of icon names to components
const iconMap: Record<string, React.ComponentType<any>> = {
    alertCircle: AlertCircle,
    arrowRight: ArrowRight,
    award: Award,
    bookmark: Bookmark,
    book: Book,
    bookOpen: BookOpen,
    box: Box,
    briefcase: Briefcase,
    brain: Brain,
    calendar: Calendar,
    check: Check,
    checkCircle: CheckCircle,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    clipboard: Clipboard,
    clipboardCheck: ClipboardCheck,
    clipboardList: ClipboardList,
    clock: Clock,
    copy: Copy,
    creditCard: CreditCard,
    download: Download,
    edit: Edit,
    externalLink: ExternalLink,
    eye: Eye,
    file: File,
    fileText: FileText,
    filter: Filter,
    flag: Flag,
    folderOpen: FolderOpen,
    gift: Gift,
    globe: Globe,
    graduationCap: GraduationCap,
    helpCircle: HelpCircle,
    heart: Heart,
    headphones: Headphones,
    home: Home,
    image: Image,
    info: Info,
    laptop: Laptop,
    lampDesk: LampDesk,
    lightbulb: Lightbulb,
    link: Link,
    list: List,
    lock: Lock,
    mail: Mail,
    mapPin: MapPin,
    medal: Medal,
    menu: Menu,
    messageSquare: MessageSquare,
    mic: Mic,
    monitor: Monitor,
    moon: Moon,
    moreHorizontal: MoreHorizontal,
    music: Music,
    package: Package,
    paperclip: Paperclip,
    phone: Phone,
    play: Play,
    plus: Plus,
    plusCircle: PlusCircle,
    presentation: Presentation,
    school: School,
    search: Search,
    send: Send,
    settings: Settings,
    share: Share,
    shieldCheck: ShieldCheck,
    shoppingBag: ShoppingBag,
    shoppingCart: ShoppingCart,
    smile: Smile,
    star: Star,
    sun: Sun,
    tag: Tag,
    thumbsUp: ThumbsUp,
    timer: Timer,
    trash: Trash,
    trophy: Trophy,
    upload: Upload,
    user: User,
    users: Users,
    userCheck: UserCheck,
    video: Video,
    videoOff: VideoOff,
    zap: Zap,
};

// Default icon name to use if requested icon doesn't exist
export const DEFAULT_ICON = 'bookOpen';

// Get all available icon names
export const availableIcons = Object.keys(iconMap);

/**
 * Gets a Lucide React icon component by name
 * 
 * @param iconName The name of the icon to retrieve
 * @param props Additional props to pass to the icon component
 * @returns The React icon component
 */
export const getIconByName = (iconName: string = DEFAULT_ICON, props: { className?: string; size?: string | number } = {}) => {
    const IconComponent = iconMap[iconName] || iconMap[DEFAULT_ICON];

    return <IconComponent {...props} />;
}; 