[[redirects]]
  from = "http://kristinamitrovic.com/*"
  to = "https://kristinamitrovic.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.kristinamitrovic.com/*"
  to = "https://kristinamitrovic.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.kristinamitrovic.com/*"
  to = "https://kristinamitrovic.com/:splat"
  status = 301
  force = true